FROM node as build_stage

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

FROM nginx

COPY --from=build_stage /app/build /user/share/nginx/html

EXPOSE 80

CMD [ "nginx", "-g",  "daemon off"]